{
  "topics": [
    "qdrant",
    "vector-database",
    "vector-search",
    "semantic-search",
    "embedding",
    "retrieval-augmented-generation",
    "rag",
    "knowledge-base",
    "information-retrieval",
    "llm",
    "mcp",
    "model-context-protocol",
    "fastapi",
    "python",
    "onnx",
    "onnxruntime",
    "fastembed",
    "docker",
    "docker-compose",
    "api-service"
  ]
}
